Months:
- 01-April
- 02-May
- 03-June
- 04-July
- 05-August
- 06-September
- 07-October
- 08-November
- 09-December
- 10-January
- 11-February
Timeslots:
- Train
- Class
- Daytime
- Evening
Confidants:
- Fool
- Magician
- Priestess
- Empress
- Emperor
- Hierophant
- Lovers
- Chariot
- Justice
- Hermit
- Fortune
- Strength
- Hanged
- Death
- Temperance
- Devil
- Tower
- Star
- Moon
- Sun
- Judgement
- Faith
- Councillor
Social Stats:
  Knowledge:   [0, 34, 82, 126, 192, 0]
  Guts:        [0, 11, 38,  68, 113, 0]
  Proficiency: [0, 12, 34,  60,  87, 0]
  Kindness:    [0, 14, 47,  94, 136, 0]
  Charm:       [0,  6, 52,  92, 132, 0]
  Random:      [0, 999, 0,   0,   0, 0]
  HP:          [0, 999, 0,   0,   0, 0]
  SP:          [0, 999, 0,   0,   0, 0]
